### PR TITLE
chore(project): migrate to Zeebe 0.13

### LINKED ISSUE #43: support 0.13
solely support the refactored latest version 0.13

### PR DESCRIPTION
**Pull request by menski**
- remove everything topic related
- remove outdated configuration files
- update client configuration
- removed outdated examples
- add groovy starter example
- starter apps are new scheduled with a fixed rate to continue creating instances
- exclude guava dependencies from jgiven-junit because it is to old for Zeebe grpc dependency 

closes #43

### CODE REVIEW

**Comment by jangalinski** [comment]
Wow, cool!

**Comment by menski** [comment]
that was a fast merge, thanks @jangalinski :balloon:

**Comment by jangalinski** [comment]
I trust you :-)    let's see what travis tells us

**Comment by menski** [comment]
@jangalinski would you be okay with me creating a new release of spring-zeebe with these changes, then I could use it in my Camunda Day presentation next week

**Comment by jangalinski** [comment]
yes, go ahead. Publish early, publish often

**Pull request merged**
