### PR TITLE
Update Spring Boot to version 2.1.4

### PR DESCRIPTION
**Pull request by spulci**
This pull request updates Zeebe Client API support to version 0.16.4 as requested by some users. It also updates Spring Boot version to 2.1.4RELEASE.

### CODE REVIEW

**Comment by jangalinski** [comment]
Nice update, but I think the "elephant in the room" is the update for 0.17 with the breaking api change and restructured process payload handling ... #52 
I won't have time to to this this week ...

**Comment by spulci** [comment]
> Nice update, but I think the "elephant in the room" is the update for 0.17 with the breaking api change and restructured process payload handling ... #52
> I won't have time to to this this week ...

I agree with you. BTW it's a small contribution while studying several Zeebe Components. BTW, hope to have time to dig into 0.17.x API to try to update Spring Zeebe in the next few weeks too.

**Comment by menski** [comment]
I created a PR for Zeebe 0.17 support (#55)

**Comment by menski** [comment]
@spulci would you like to rebase your changes to the current master, i.e. after the 0.17.0 upgrade. So we can merge your remaining changes of this PR?

**Comment by spulci** [comment]
> @spulci would you like to rebase your changes to the current master, i.e. after the 0.17.0 upgrade. So we can merge your remaining changes of this PR?

Sure @menski  :) I think that I can add only support to Spring Boot 2.1.4RELEASE as reporter in #51

**Comment by spulci** [comment]
Ok, rebased and updated to Spring Boot 2.1.4 to close #51 . 

Tested locally running starter and worker client on a 0.17.0 broker instance: works great! Please @jangalinski and @menski review and test. Let me know other changes if needed (that's my first concrete contribution, I need to learn a lot).

**Comment by menski** [comment]
LGTM, thanks for the contribution :+1:

**Pull request merged**
