### PR TITLE
104 more configurations

### PR DESCRIPTION
**Pull request by ajeans**
@salaboy this is basically https://github.com/zeebe-io/spring-zeebe/pull/97 (commit from @wenminglei properly cherrypicked)  with an additional commit on top to add some trivial unit testing.

Not sure this is what you had in mind, do not hesitate to provide feedback if you had something better in mind.

### CODE REVIEW

**Comment by salaboy** [comment]
@ajeans thanks for this.. I will close @wenminglei  PR .. but you need to rebase this one to avoid conflict.. can you please do that ?

**Comment by ajeans** [comment]
@salaboy rebase done and pushed out

let's find out if travis likes it :)

**Comment by salaboy** [comment]
@ajeans small issue I believe:

```
[ERROR] /home/travis/build/zeebe-io/spring-zeebe/client/spring-zeebe/src/test/java/io/zeebe/spring/client/bean/value/factory/ReadZeebeWorkerValueTest.java:[65,22] builder() is not public in io.zeebe.spring.client.bean.MethodInfo; cannot be accessed from outside package
```

**Comment by ajeans** [comment]
@salaboy ok that was embarrassing... :blush: 

The `builder()` should have been public to allow testing... this was trivial indeed.

But once hooked up, the unit test failed because I failed to hook the new builder fields to the object... I can't see how I convinced myself that it built locally, it didn't... Oh well, this was done on a Friday so that will be my excuse...

The build is queued on travis ci and it actually builds locally this time, so fingers crossed.

**Pull request merged**
