### PR TITLE
ci(jenkins): add jenkins distro release job

### PR DESCRIPTION
**Pull request by menski**
*Note*: as the examples are not build during the release the parent version
in the examples pom is not adjusted and has to be modified manually after the
release.

related to zeebe-io/zeebe#549

### CODE REVIEW

**Comment by menski** [comment]
The job only uploads the artifacts to Camunda nexus and maven central. If we want also a GitHub release we need a list for files to upload. Then I can add the GitHub release part to the job.

**Comment by jangalinski** [comment]
The release should contain:

* spring-zeebe-broker
* spring-zeebe-broker-starter

* spring-zeebe
* spring-zeebe-starter

**Comment by jangalinski** [comment]
You are right about the version of the examples ... didn't take that into account. But still I think npot having examples polluting the repo is worth the manual effort

**Comment by menski** [comment]
I added the GitHub release step as an extra commit

**Pull request merged**
