### PR TITLE
feat(cloud): Easy configuration for Camunda Cloud (related to https:/…

### PR DESCRIPTION
**Pull request by berndruecker**
…/github.com/zeebe-io/spring-zeebe/issues/81)

### CODE REVIEW

**Comment by berndruecker** [comment]
@saig0 @ArtunSubasi @salaboy Ok with you? Or comments?

**Comment by saig0** [comment]
Nice :+1: 
From the README, it is not clear that the `credentialsCachePath` is optional but it seems so.

**Comment by berndruecker** [comment]
You are right - I simply removed it to avoid that people need to think (why should I adjust it anyway?)

**Comment by ArtunSubasi** [comment]
> You are right - I simply removed it to avoid that people need to think

Bernd, I like the way you think 👍

**Pull request merged**
