### PR TITLE
Upgrade to Zeebe 0.7.0

### PR DESCRIPTION
**Pull request by menski**
Hi @jangalinski,

I started to migrate spring-zeebe to the upcoming 0.7.0 changes. As 0.7.0 is not yet released this is more a tracking pull requests. But currently it at least compiles and the examples work. Feel free to add more changes to the branch.

Cheers,
Sebastian

### CODE REVIEW

**Comment by menski** [comment]
Hi @jangalinski,

this update can now be merged to master. Are there any other changes you want to make before the next release? Otherwise I would make a release after the merge if that is okay for you.

Cheers,
Sebastian

**Comment by jangalinski** [comment]
Cool. Let me check this when I am back at my machine, but I think I am fine with just releasing

**Comment by menski** [comment]
Thanks for merging. Can I go ahead and create a new release in the next days or is there something blocking?

**Comment by jangalinski** [comment]
yes, please do so

**Pull request merged**
