### PR TITLE
chore(deps): remove lombok dependency

### PR DESCRIPTION
**Pull request by ajeans**
This is requested in #42 

Notes:
- This is done in one gigantic commit, I can split it into more commits if it is easier to review
- I replaced SneakyThrows with a RuntimeException wrapping the actual exception, this may change behaviour for clients
- Lots of churn in the diff. I think my editor formatted the files correctly according to the .editorconfig, but the project was not completely formatted with that.

This branch has not been tested at all (outside the few unit tests in there). 
I will probably test it on Monday, but I might have broken things.

### CODE REVIEW

**Comment by salaboy** [comment]
@ajeans I am totally ok with this PR, but one question: 
Can we just leave Lombok for the examples? That will be a good validation that in examples, and end-user applications Lombok can be used, but we just don't want it inside the client code.. 

Also, can you please sign the CLA?

**Comment by ajeans** [comment]
@salaboy sure, I will restore it for the examples.

Regarding the CLA, I pinged legal at $company yesterday, I should be able to sign it soon.

**Comment by ajeans** [comment]
@salaboy this should be good to go now ;-)

**Comment by ajeans** [comment]
@salaboy friendly reminder, anything I can do to help this land?

**Pull request merged**
